# Colors (One Dark)

# Default colors
[colors.primary]
# background = '#111111'
background = '#1c1f26'
foreground = '#abb2bf'

# Normal colors
[colors.normal]
black   = '#1e2127'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#abb2bf'

# Bright colors
[colors.bright]
black   = '#5c6370'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#ffffff'

[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular"}
size = 14

[window]
opacity = 0.9
padding = { x = 20, y = 20}
